before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-dev libxslt-dev cmake
    - gem update --system
    - bundle update

cache:
    - directories: 
        - $HOME/.m2

jdk:
    - openjdk8

language: ruby
rvm:
       - 2.4.4
       - 2.5.1
       - jruby-9.2.0.0



